language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy-7.1.1
install:
  - pip install pip --upgrade
  - pip install .
script:
  - pylint cfsslcli
  - python setup.py test
  - python setup.py build
